import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Providers from "./Provider";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Pricing King",
  description: "Generated by create next app",
};



export default function RootLayout({ children }) {
  return (

    <html lang="en" >
      <body>
        <Providers>
          <div>
            <Header></Header>
            {children}
          </div>
        </Providers>
      </body>

    </html >


  );
}
