import { Inter } from "next/font/google";
import "../globals.css";
import Providers from "../Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Pricing King",
    description: "Generated by create next app",
};



export default function LoadingLayout({ children }) {
    return (
        <div>
            <Providers>
                <div>{children}</div>
            </Providers>
        </div>
    );
}
